/*DDL-Script 
   PROJECT:    CITY MAP
  STUDENTS:    LADAR | NEUHERZ
   VERSION:    0.2
      DATE:    2015-11-07 | UPDATE 2015-11-24
   SUBJECT: DB_ANW | HABIGER
*/

--CREATE TABLE SCRIPT
--SCHEME: TICKETS
CREATE TABLE TICKETS.TICKETTYPE (
  TicketType_ID  NUMERIC PRIMARY KEY,
  Type  VARCHAR(200) NOT NULL); 
  
CREATE TABLE TICKETS.TICKETTYPEPRICE (
  TicketType_ID  NUMERIC,
  ValidFrom  DATE,
  BasePrice NUMERIC(8,2) NOT NULL,
  PRIMARY KEY (TicketType_ID, ValidFrom) ); 

CREATE TABLE TICKETS.DISCOUNT (
  Discount_ID NUMERIC PRIMARY KEY,
  Description VARCHAR(200),
  Percentage NUMERIC(3) NOT NULL);   

CREATE TABLE TICKETS.TICKETTYPE_DISCOUNT (
  Discount_ID NUMERIC,
  TicketType_ID  NUMERIC,
  PRIMARY KEY (Discount_ID, TicketType_ID)); 
  
CREATE TABLE TICKETS.TICKET (
  TicketID NUMERIC PRIMARY KEY,
  TicketType_ID  NUMERIC NOT NULL,
  Discount_ID  NUMERIC NOT NULL,
  Price NUMERIC(3) NOT NULL,
  PurchaseDate DATE NOT NULL);
  
   
--CREATE TABLE SCRIPT
--SCHEME: CITY MAP
CREATE TABLE CITYMAP.RIDETYPE (
  RideType_ID NUMERIC PRIMARY KEY,
  Type  VARCHAR(200) NOT NULL);  
  
CREATE TABLE CITYMAP.RIDE (
  Ride_ID NUMERIC PRIMARY KEY,
  Description  VARCHAR(200) NOT NULL,
  Line_ID NUMERIC NOT NULL,
  RideType_ID NUMERIC NOT NULL);    
  
CREATE TABLE CITYMAP.LINE (
  Line_ID NUMERIC PRIMARY KEY,
  Description  VARCHAR(200) NOT NULL,
  Vehicle_ID NUMERIC NOT NULL);   
  
CREATE TABLE CITYMAP.VEHICLE (
  Vehicle_ID NUMERIC PRIMARY KEY,
  Description  VARCHAR(200) NOT NULL); 

CREATE TABLE CITYMAP.STATION (
  Station_ID NUMERIC PRIMARY KEY,
  Description  VARCHAR(200) NOT NULL);   
  
CREATE TABLE CITYMAP.VEHICLE_STATION (
  Station_ID NUMERIC,
  Vehicle_ID NUMERIC,
  PRIMARY KEY (Station_ID, Vehicle_ID)); 

CREATE TABLE CITYMAP.STOP (
  Station_ID NUMERIC,
  Ride_ID NUMERIC,
  Halt_No NUMERIC,
  WaitTime NUMERIC(3),
  TimeToNextStop NUMERIC(3),
  --TODO: TRIGGER Halt_No
  PRIMARY KEY (Ride_ID, Halt_No));       

CREATE TABLE citymap.rideonday
(
  ride_id numeric,
  ridestarttime timestamp,
  --POSSIBLE ATTRIBUTES: Driver,
  --                     Specific Vehicle with Vehicle NUMERIC (License Plate, etc.)
  PRIMARY KEY (ride_id, ridestarttime)
);
 
CREATE TABLE CITYMAP.DELAY (
  Ride_ID NUMERIC,
  RideStartTime TIMESTAMP,
  DelayInMinutes NUMERIC(3),
  Reason VARCHAR(255),
  PRIMARY KEY (Ride_ID, RideStartTime)); 

  --ALTER TABLE SCRIPT
--SCHEME: TICKETS
   ALTER TABLE TICKETS.TICKETTYPEPRICE
ADD CONSTRAINT tickettypeprice_fk
   FOREIGN KEY (TicketType_ID)
    REFERENCES TICKETS.TICKETTYPE (TicketType_ID);
   
   ALTER TABLE TICKETS.TICKETTYPE_DISCOUNT
ADD CONSTRAINT TICKETTYPE_DISCOUNT_DIS_FK
   FOREIGN KEY (Discount_ID)
    REFERENCES TICKETS.DISCOUNT (Discount_ID);

   ALTER TABLE TICKETS.TICKETTYPE_DISCOUNT
ADD CONSTRAINT TICKETTYPE_DISCOUNT_TT_FK
   FOREIGN KEY (TicketType_ID)
    REFERENCES TICKETS.TICKETTYPE (TicketType_ID);
    
       ALTER TABLE TICKETS.TICKET
ADD CONSTRAINT TICKET_FK
   FOREIGN KEY (TicketType_ID, Discount_ID)
    REFERENCES TICKETS.TICKETTYPE_DISCOUNT (TicketType_ID, Discount_ID);
    
--ALTER TABLE SCRIPT
--SCHEME: CITY MAP
   ALTER TABLE CITYMAP.LINE
ADD CONSTRAINT LINE_FK
   FOREIGN KEY (Vehicle_ID)
    REFERENCES CITYMAP.VEHICLE (Vehicle_ID);
    
   ALTER TABLE CITYMAP.RIDE
ADD CONSTRAINT RIDE_L_FK
   FOREIGN KEY (Ridetype_ID)
    REFERENCES CITYMAP.RIDETYPE (Ridetype_ID);
    
   ALTER TABLE CITYMAP.RIDE
ADD CONSTRAINT RIDE_FT_FK
   FOREIGN KEY (Line_ID)
    REFERENCES CITYMAP.LINE (Line_ID);
    
   ALTER TABLE CITYMAP.VEHICLE_STATION
ADD CONSTRAINT VEHICLE_STATION_V_FK
   FOREIGN KEY (Vehicle_ID)
    REFERENCES CITYMAP.VEHICLE (Vehicle_ID);
    
   ALTER TABLE CITYMAP.VEHICLE_STATION
ADD CONSTRAINT VEHICLE_STATION_S_FK
   FOREIGN KEY (Station_ID)
    REFERENCES CITYMAP.STATION (Station_ID);
    
       ALTER TABLE CITYMAP.STOP
ADD CONSTRAINT STOP_RI_FK
   FOREIGN KEY (Ride_ID)
    REFERENCES CITYMAP.RIDE (Ride_ID);
    
           ALTER TABLE CITYMAP.STOP
ADD CONSTRAINT STOP_ST_FK
   FOREIGN KEY (Station_ID)
    REFERENCES CITYMAP.STATION (Station_ID);

           ALTER TABLE CITYMAP.RIDEONDAY
ADD CONSTRAINT RIDEONDAY_FK
   FOREIGN KEY (Ride_ID)
    REFERENCES CITYMAP.RIDE (Ride_ID);
    
ALTER TABLE CITYMAP.DELAY
ADD CONSTRAINT DELAY_FK
   FOREIGN KEY (Ride_ID, RideStartTime)
    REFERENCES CITYMAP.RIDEONDAY (Ride_ID, RideStartTime);