/*DDL-Script 
   PROJECT:    CITY MAP
  STUDENTS:    LADAR | NEUHERZ
   VERSION:    0.2
      DATE:    2015-11-07 | UPDATE 2015-11-24
   SUBJECT: DB_ANW | HABIGER
*/

--CREATE TABLE SCRIPT
--SCHEME: TICKETS
CREATE TABLE NEUHERZA15.TICKETTYPE (
  TicketType_ID  NUMBER PRIMARY KEY,
  Type  VARCHAR2(200) NOT NULL); 
  
CREATE TABLE NEUHERZA15.TICKETTYPEPRICE (
  TicketType_ID  NUMBER,
  ValidFrom  DATE,
  BasePrice NUMBER(8,2) NOT NULL,
  PRIMARY KEY (TicketType_ID, ValidFrom) ); 

CREATE TABLE NEUHERZA15.DISCOUNT (
  Discount_ID NUMBER PRIMARY KEY,
  Description VARCHAR2(200),
  Percentage NUMBER(3) NOT NULL);   

CREATE TABLE NEUHERZA15.TICKETTYPE_DISCOUNT (
  Discount_ID NUMBER,
  TicketType_ID  NUMBER,
  PRIMARY KEY (Discount_ID, TicketType_ID)); 
  
CREATE TABLE NEUHERZA15.TICKET (
  TicketID NUMBER PRIMARY KEY,
  TicketType_ID  NUMBER NOT NULL,
  Discount_ID  NUMBER NOT NULL,
  Price NUMBER(3) NOT NULL,
  PurchaseDate DATE NOT NULL);
  
   
--CREATE TABLE SCRIPT
--SCHEME: CITY MAP
CREATE TABLE NEUHERZA15.RIDETYPE (
  RideType_ID NUMBER PRIMARY KEY,
  Type  VARCHAR(200) NOT NULL);  
  
CREATE TABLE NEUHERZA15.RIDE (
  Ride_ID NUMBER PRIMARY KEY,
  Description  VARCHAR(200) NOT NULL,
  Line_ID NUMBER NOT NULL,
  RideType_ID NUMBER NOT NULL);    
  
CREATE TABLE NEUHERZA15.LINE (
  Line_ID NUMBER PRIMARY KEY,
  Description  VARCHAR(200) NOT NULL,
  Vehicle_ID NUMBER NOT NULL);   
  
CREATE TABLE NEUHERZA15.VEHICLE (
  Vehicle_ID NUMBER PRIMARY KEY,
  Description  VARCHAR(200) NOT NULL); 

CREATE TABLE NEUHERZA15.STATION (
  Station_ID NUMBER PRIMARY KEY,
  Description  VARCHAR(200) NOT NULL);   
  
CREATE TABLE NEUHERZA15.VEHICLE_STATION (
  Station_ID NUMBER,
  Vehicle_ID NUMBER,
  PRIMARY KEY (Station_ID, Vehicle_ID)); 

CREATE TABLE NEUHERZA15.STOP (
  Station_ID NUMBER,
  Ride_ID NUMBER,
  Halt_No NUMBER,
  WaitTime NUMBER(3),
  TimeToNextStop NUMBER(3),
  --TODO: TRIGGER Halt_No
  PRIMARY KEY (Ride_ID, Halt_No));       

CREATE TABLE NEUHERZA15.RIDEONDAY (
  Ride_ID NUMBER,
  RideStartTime DATE,
  --POSSIBLE ATTRIBUTES: Driver, 
  --                     Specific Vehicle with Vehicle Number (License Plate, etc.)
  PRIMARY KEY (Ride_ID, RideStartTime)); 
 
CREATE TABLE NEUHERZA15.DELAY (
  Ride_ID NUMBER,
  RideStartTime DATE,
  DelayInMinutes NUMBER(3),
  Reason VARCHAR(255),
  PRIMARY KEY (Ride_ID, RideStartTime)); 

  --ALTER TABLE SCRIPT
--SCHEME: TICKETS
   ALTER TABLE NEUHERZA15.TICKETTYPEPRICE
ADD CONSTRAINT tickettypeprice_fk
   FOREIGN KEY (TicketType_ID)
    REFERENCES NEUHERZA15.TICKETTYPE (TicketType_ID);
   
   ALTER TABLE NEUHERZA15.TICKETTYPE_DISCOUNT
ADD CONSTRAINT TICKETTYPE_DISCOUNT_DIS_FK
   FOREIGN KEY (Discount_ID)
    REFERENCES NEUHERZA15.DISCOUNT (Discount_ID);

   ALTER TABLE NEUHERZA15.TICKETTYPE_DISCOUNT
ADD CONSTRAINT TICKETTYPE_DISCOUNT_TT_FK
   FOREIGN KEY (TicketType_ID)
    REFERENCES NEUHERZA15.TICKETTYPE (TicketType_ID);
    
       ALTER TABLE NEUHERZA15.TICKET
ADD CONSTRAINT TICKET_FK
   FOREIGN KEY (TicketType_ID, Discount_ID)
    REFERENCES NEUHERZA15.TICKETTYPE_DISCOUNT (TicketType_ID, Discount_ID);
    
--ALTER TABLE SCRIPT
--SCHEME: CITY MAP
   ALTER TABLE NEUHERZA15.LINE
ADD CONSTRAINT LINE_FK
   FOREIGN KEY (Vehicle_ID)
    REFERENCES NEUHERZA15.VEHICLE (Vehicle_ID);
    
   ALTER TABLE NEUHERZA15.RIDE
ADD CONSTRAINT RIDE_L_FK
   FOREIGN KEY (Ridetype_ID)
    REFERENCES NEUHERZA15.RIDETYPE (Ridetype_ID);
    
   ALTER TABLE NEUHERZA15.RIDE
ADD CONSTRAINT RIDE_FT_FK
   FOREIGN KEY (Line_ID)
    REFERENCES NEUHERZA15.LINE (Line_ID);
    
   ALTER TABLE NEUHERZA15.VEHICLE_STATION
ADD CONSTRAINT VEHICLE_STATION_V_FK
   FOREIGN KEY (Vehicle_ID)
    REFERENCES NEUHERZA15.VEHICLE (Vehicle_ID);
    
   ALTER TABLE NEUHERZA15.VEHICLE_STATION
ADD CONSTRAINT VEHICLE_STATION_S_FK
   FOREIGN KEY (Station_ID)
    REFERENCES NEUHERZA15.STATION (Station_ID);
    
       ALTER TABLE NEUHERZA15.STOP
ADD CONSTRAINT STOP_RI_FK
   FOREIGN KEY (Ride_ID)
    REFERENCES NEUHERZA15.RIDE (Ride_ID);
    
           ALTER TABLE NEUHERZA15.STOP
ADD CONSTRAINT STOP_ST_FK
   FOREIGN KEY (Station_ID)
    REFERENCES NEUHERZA15.STATION (Station_ID);

           ALTER TABLE NEUHERZA15.RIDEONDAY
ADD CONSTRAINT RIDEONDAY_FK
   FOREIGN KEY (Ride_ID)
    REFERENCES NEUHERZA15.RIDE (Ride_ID);
    
               ALTER TABLE NEUHERZA15.DELAY
ADD CONSTRAINT DELAY_FK
   FOREIGN KEY (Ride_ID, RideStartTime)
    REFERENCES NEUHERZA15.RIDEONDAY (Ride_ID, RideStartTime);​